#include "SEGGER_SYSVIEW.h"
#include "SEGGER_SYSVIEW_Conf.h"
#include "stm32l4xx.h"

void SEGGER_SYSVIEW_Conf(void) {
    SEGGER_SYSVIEW_Init(SEGGER_SYSVIEW_TIMESTAMP_FREQ, SEGGER_SYSVIEW_CPU_FREQ, 0, 0);
    SEGGER_SYSVIEW_SetRAMBase(SEGGER_SYSVIEW_RAM_BASE);
}