#ifndef RTOS_CONFIG_H
#define RTOS_CONFIG_H

#define RTOS_TASK_STACK_SIZE  (128u)

#define RTOS_APP_TASK_COUNT   2u
#define RTOS_TOTAL_TASK_COUNT (RTOS_APP_TASK_COUNT + 1u)
#define RTOS_IDLE_TASK_INDEX  RTOS_APP_TASK_COUNT

#endif