#ifndef RTOS_CONFIG_H
#define RTOS_CONFIG_H

#define RTOS_TASK_STACK_SIZE    (128u)

#define RTOS_MAX_TASKS          (8u)
#define RTOS_MAX_PRIORITIES     (8u)

#define RTOS_IDLE_TASK_PRIORITY (0u)
#define RTOS_USER_MIN_PRIORITY  (1u)
#define RTOS_USER_MAX_PRIORITY  (RTOS_MAX_PRIORITIES - 1u)

#endif